export default

[{
      vote_count: 141,
      id: 40096,
      video: false,
      vote_average: 8.3,
      title: 'A Dog\'s Will',
      popularity: 33.508658,
      poster_path: '/uHEmM49YphluJnGep8Ef1qwD2QX.jpg',
      original_language: 'pt',
      original_title: 'O Auto da Compadecida',
      genre_ids: [12, 35, 18],
      backdrop_path: '/alQqTpmEkxSLgajfEYTsTH6nAKB.jpg',
      adult: false,
      overview: 'The lively João Grilo and the sly Chicó are poor guys living in the hinterland who cheat a bunch of people in a small Northeast Brazil town. But when they die, they have to be judged by Christ, the Devil and the Virgin Mary, before they are admitted to paradise.',
      release_date: '2000-09-10'
    }, {
      vote_count: 2940,
      id: 591,
      video: false,
      vote_average: 6.5,
      title: 'The Da Vinci Code',
      popularity: 18.428555,
      poster_path: '/5IqaT3fza0Y9vKazjGwDGsNuuS8.jpg',
      original_language: 'en',
      original_title: 'The Da Vinci Code',
      genre_ids: [53, 9648],
      backdrop_path: '/hcAMO4LF6G2hvsTpNgmY1kFj3jJ.jpg',
      adult: false,
      overview: 'When the curator of the Louvre is found murdered in the famed museum\'s hallowed halls, Harvard professor, Robert Langdon and cryptographer, Sophie Neve must untangle a deadly web of deceit involving the works of Leonardo da Vinci.',
      release_date: '2006-05-17'
    }, {
      vote_count: 485,
      id: 318917,
      video: false,
      vote_average: 6.8,
      title: 'Look Who\'s Back',
      popularity: 9.575702,
      poster_path: '/3nQebcc0bhUO4wsK8wprL8w7kg5.jpg',
      original_language: 'de',
      original_title: 'Er ist wieder da',
      genre_ids: [35],
      backdrop_path: '/gs2q4OmQ4ulVELwkeGkm5kGkEJc.jpg',
      adult: false,
      overview: 'Adolf Hitler wakes up in a vacant lot in Berlin, with no knowledge of anything that happened after 1945. Homeless and destitute. Although everyone recognizes him, nobody believes that he is Hitler; instead, they think he is either a comedian, or a method actor.',
      release_date: '2015-10-08'
    }, {
      vote_count: 3,
      id: 80207,
      video: false,
      vote_average: 5,
      title: 'Bambina',
      popularity: 8.000889,
      poster_path: '/bRVDCoOW1UrYkaYrrOnO5ltMC0M.jpg',
      original_language: 'en',
      original_title: 'Le farò da padre',
      genre_ids: [35, 18, 10749],
      backdrop_path: '/z22R2j8O3HIKmNQkj6v5cXLDhL4.jpg',
      adult: false,
      overview: 'In order to convince Raimonda, a wealthy noble woman, to finance his project for a holiday resort, Saverio gets engaged to Clotilde, her mentally-disturbed and sex-obsessed adolescent daughter. He plans to have her kidnapped and raped by an accomplice so she won\'t be a virgin anymore and he\'ll have an excuse to get out of the impending marriage. But what he doesn\'t plan is to fall in love with the girl...',
      release_date: '1974-09-17'
    }, {
      vote_count: 2,
      id: 123605,
      video: false,
      vote_average: 2,
      title: 'Da',
      popularity: 1.365376,
      poster_path: '/3juL2T0qwcjjrga4Oj4VPPa00f3.jpg',
      original_language: 'en',
      original_title: 'Da',
      genre_ids: [],
      backdrop_path: null,
      adult: false,
      overview: 'A New York playwright is summoned to Ireland to bury his father (his "Da"). While at his boyhood home, he encounters his father\'s spirit and relives memories both pleasant and not.',
      release_date: '1988-04-29'
    }, {
      vote_count: 53,
      id: 236325,
      video: false,
      vote_average: 5.6,
      title: 'Stay Away from Me',
      popularity: 5.829802,
      poster_path: '/w5sn3OZFSqHBqm5hN6WID4R8gdc.jpg',
      original_language: 'it',
      original_title: 'Stai lontana da me',
      genre_ids: [35, 10749],
      backdrop_path: '/fbf3acssxM3uq2fcEUZUKX5Gq4V.jpg',
      adult: false,
      overview: 'Jacopo (Enrico Brignano) has a serious problem. He may be a brilliant marriage guidance counsellor, but he can never manage to have a steady relationship for more than two weeks. And for good reason: since he was very young, Jacopo has been cursed and brought bad luck to every woman who has fallen in love with him. Really bad luck. Because of this, he has vowed to stay away from women, for their own good. But the moment he lays eyes on Sara (a radiant Ambra Angiolini, The Immature and The Immature: The Trip) at a friend’s birthday party, he is smitten.  Despite his resistance, the two fall head over heels leading to back-to-back, laugh-out-loud moments of disaster! Sara will quickly learn the consequences of her choice as the limits of her love are put to the test in this smart, stylish and very loveable romantic comedy.',
      release_date: '2013-11-14'
    }, {
      vote_count: 64,
      id: 419507,
      video: false,
      vote_average: 3.7,
      title: 'Fuga da Reuma Park',
      popularity: 5.442754,
      poster_path: '/fuplKoMM5aSW9d5hQkb52GWvGjy.jpg',
      original_language: 'it',
      original_title: 'Fuga da Reuma Park',
      genre_ids: [35],
      backdrop_path: '/bW9DceNferMoL2RmKrU9yeoNOMM.jpg',
      adult: false,
      overview: '',
      release_date: '2016-12-15'
    }, {
      vote_count: 66,
      id: 173847,
      video: false,
      vote_average: 6.2,
      title: 'Amiche da morire',
      popularity: 4.791344,
      poster_path: '/le0FaFTh3sVozyDriUG7Ne0D8JT.jpg',
      original_language: 'en',
      original_title: 'Amiche da morire',
      genre_ids: [10749, 80, 35],
      backdrop_path: '/gDagfGssW8J9AYLFnDh3LOYRVWS.jpg',
      adult: false,
      overview: 'Three very different women who are hiding a secret are forced to work together to save their own skin.',
      release_date: '2013-03-07'
    }, {
      vote_count: 3,
      id: 377148,
      video: false,
      vote_average: 5.5,
      title: 'Letters from War',
      popularity: 4.417428,
      poster_path: '/5kLihCF8agnlcYvieNxnULNLEJC.jpg',
      original_language: 'pt',
      original_title: 'Cartas da Guerra',
      genre_ids: [18, 10752],
      backdrop_path: '/edIIPcHBA5JtP1ynZ17jvaJzS3t.jpg',
      adult: false,
      overview: 'In 1971, António Lobo Antunes\' life is brutally interrupted when he is drafted into the Portuguese Army to serve as a doctor in one of the worst zones of the Colonial War – the East of Angola. Away from everything dear he writes letters to his wife while he is immersed in an increasingly violent setting. While he moves between several military posts he falls in love for Africa and matures politically. At his side, an entire generation struggles and despairs for the return home. In the uncertainty of war events, only the letters can make him survive.',
      release_date: '2016-09-01'
    }, {
      vote_count: 10,
      id: 381066,
      video: false,
      vote_average: 7,
      title: 'Jules and Dolores',
      popularity: 4.032192,
      poster_path: '/47quJOkCy25eVCOmiL3hzSge96J.jpg',
      original_language: 'pt',
      original_title: 'O Roubo da Taça',
      genre_ids: [35],
      backdrop_path: null,
      adult: false,
      overview: 'On December 19th, 1983, the dream was taken away. The most coveted trophy of all time, the Jules Rimet Cup disappeared from the headquarters of CBF, the Brazilian Football Association. Let me explain: every 4 years FIFA holds a Football World Cup. Back then, only a country that won the Cup three times could keep the trophy for good. This privilege was reserved to Brazil when they won for the 3rd time in 1970. The beautiful trophy was kept as a symbol of superiority in the headquarters of CBF, in Rio de Janeiro. “Jules and Dolores” is a pop comedy that tell us the real, preposterous and unusual story behind this theft.',
      release_date: '2016-09-08'
    }, {
      vote_count: 20,
      id: 341244,
      video: false,
      vote_average: 8.1,
      title: 'A Film Life',
      popularity: 5.572763,
      poster_path: '/tZ544US8qblE1saWrvbH2U17vUD.jpg',
      original_language: 'pt',
      original_title: 'O Filme da Minha Vida',
      genre_ids: [18],
      backdrop_path: '/nEfoTwiItxMMrchH9zNEXQhusmx.jpg',
      adult: false,
      overview: 'The sierras of southern Brazil, 1963. The son of an American man and a Brazilian woman, Tony is a young man with a profound love of cinema and poetry. After graduating from college he returns to his small town in rural Brazil, to find out that his father had left for good. Tony then looks for the company of his fathers friends in search of information and references of a lost male role-model. He becomes a school teacher and a male figure to kids, in an attempt to provide them with something he lacks himself. A series of developments lead him to a surprising final lead on his fathers\' whereabouts and reasons for leaving.',
      release_date: '2017-08-03'
    }, {
      vote_count: 1,
      id: 396512,
      video: false,
      vote_average: 6,
      title: 'Seit du da bist',
      popularity: 3.910721,
      poster_path: '/l7kykNCRLdruWMsolRsMPYeQa7i.jpg',
      original_language: 'de',
      original_title: 'Seit du da bist',
      genre_ids: [18, 35, 10770],
      backdrop_path: '/fZUwxaq6vaDomrPkjcxltTirm2p.jpg',
      adult: false,
      overview: 'German television film by Michael Hofmann.',
      release_date: '2016-05-06'
    }, {
      vote_count: 5,
      id: 359806,
      video: false,
      vote_average: 6.4,
      title: 'Em Nome da Lei',
      popularity: 3.767406,
      poster_path: '/bapeOn82dybU5pxJIQISlmpMysZ.jpg',
      original_language: 'pt',
      original_title: 'Em Nome da Lei',
      genre_ids: [53, 28, 18, 9648],
      backdrop_path: '/uaYOSh6mKJYVHzFHjSRiSfz0i0E.jpg',
      adult: false,
      overview: 'The journey of idealistic Vitor, a young federal judge who decides to dismantle the mafia that dominates the border between Brazil and Paraguay. Inspired by true events.',
      release_date: '2016-04-21'
    }, {
      vote_count: 0,
      id: 480420,
      video: false,
      vote_average: 0,
      title: 'O Nome da Morte',
      popularity: 3.684643,
      poster_path: '/q2gX2SmoMar4VOVDcc8dhpT5oF2.jpg',
      original_language: 'en',
      original_title: 'O Nome da Morte',
      genre_ids: [],
      backdrop_path: null,
      adult: false,
      overview: 'The story of Julio Batista, a professional killer who was responsible for almost 500 hundred murders in Brazil.',
      release_date: '2017-10-10'
    }, {
      vote_count: 45,
      id: 38528,
      video: false,
      vote_average: 7.6,
      title: 'Febbre da Cavallo',
      popularity: 3.626872,
      poster_path: '/AhmxFGC9I1Xp8DZUkd0ViJAuFCd.jpg',
      original_language: 'it',
      original_title: 'Febbre da cavallo',
      genre_ids: [35],
      backdrop_path: null,
      adult: false,
      overview: 'Bruno Fioretti, known as "Mandrake", is an inveterate gambler who never misses a day at the horse racing track in Rome. He is doubly unlucky: he bets too much on one horse, and his wife is sleeping with his best friend because Mandrake is always at the track. Penniless and cuckolded, Mandrake decides to make one last bet.',
      release_date: '1976-01-01'
    }, {
      vote_count: 32,
      id: 49397,
      video: false,
      vote_average: 6.8,
      title: 'Death Rides a Horse',
      popularity: 3.529763,
      poster_path: '/7xJLGcKGIPs2a4dQUuLDPFCRg0f.jpg',
      original_language: 'it',
      original_title: 'Da uomo a uomo',
      genre_ids: [37],
      backdrop_path: '/AuyhlhLpioBB7igPqMBBWi0Q6wZ.jpg',
      adult: false,
      overview: 'Death Rides a Horse (aka Da uomo a uomo, or As Man to Man) is a 1967 spaghetti western directed by Giulio Petroni, written by Luciano Vincenzoni, and starring Lee Van Cleef and John Phillip Law. Bill Meceita, a boy whose family was murdered in front of him by a gang, sets out 15 years later to exact revenge. On his journey, he finds himself continually sparring and occasionally cooperating with Ryan, a gunfighter on his own quest for vengeance, who knows more than he says about Bill\'s tragedy. The film has lapsed into public domain.',
      release_date: '1967-08-31'
    }, {
      vote_count: 61,
      id: 13386,
      video: false,
      vote_average: 7.6,
      title: 'Ricomincio da tre',
      popularity: 3.489214,
      poster_path: '/3qbSRogkAQCTTYVmRNV6P8zTGw8.jpg',
      original_language: 'it',
      original_title: 'Ricomincio da tre',
      genre_ids: [35],
      backdrop_path: '/bcErsOREZUXecvwnfmVn5ruhl94.jpg',
      adult: false,
      overview: 'Gaetano, giovane napoletano, decide di lasciare casa, lavoro ed amici, per cercare altri momenti di vita e conoscere altre persone. Arriva a Firenze, a casa della zia. In un ambulatorio, dove capita per caso, conosce Marta e se ne innammora. Dopo una serie di divertenti situazioni (un vecchio amico dalla parlantina inarrestabile arriva da Napoli; la matura zia ed il suo attempato amante; un giovane prete Americano che vuole coinvolgerlo per forza nelle sue visite evangeliche; l\'incontro con Riccardino, un giovane frustrato da una madre oppressiva; il padre che aspetta il miracolo della ricrescita di una mano amputata; etc.) Gaetano decide di restare a Firenze e di fare da padre al figlio che Marta aspetta, anche se la ragazza non vuole rivelare con esattezza il nome del padre.',
      release_date: '1981-03-05'
    }, {
      vote_count: 16,
      id: 337708,
      video: false,
      vote_average: 6.1,
      title: 'Vai que Dá Certo 2',
      popularity: 4.803353,
      poster_path: '/sPuJMtIvaxnMgIXarkn5cTW5H9H.jpg',
      original_language: 'pt',
      original_title: 'Vai que Dá Certo 2',
      genre_ids: [35],
      backdrop_path: '/f8OleP5HUHsdXn6CwsnWpEcnAe5.jpg',
      adult: false,
      overview: '',
      release_date: '2016-01-07'
    }, {
      vote_count: 38,
      id: 180371,
      video: false,
      vote_average: 6.1,
      title: 'Vai Que Dá Certo',
      popularity: 3.238913,
      poster_path: '/fN4jTgLXmhZYRGbwheknfB4vRes.jpg',
      original_language: 'pt',
      original_title: 'Vai Que Dá Certo',
      genre_ids: [35],
      backdrop_path: '/iP0itNak9PKQDV0DhF7WAfMw6dj.jpg',
      adult: false,
      overview: '5 friends have a plan to rob a transporter that can change their lives.',
      release_date: '2013-03-22'
    }, {
      vote_count: 26,
      id: 264001,
      video: false,
      vote_average: 5.1,
      title: 'Un matrimonio da favola',
      popularity: 3.107938,
      poster_path: '/bwNp91UJBY3xtvcWvHB8UuLWE7q.jpg',
      original_language: 'it',
      original_title: 'Un matrimonio da favola',
      genre_ids: [35],
      backdrop_path: '/vdRen3j6H50oXWtIyOZzniUkCpg.jpg',
      adult: false,
      overview: '',
      release_date: '2014-04-10'
    }]

